# Generated by Django 5.2.6 on 2025-09-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_compte_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
