# Generated by Django 5.2.6 on 2025-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_compte_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='cours_pdfs/'),
        ),
    ]
