# Generated by Django 5.2.6 on 2025-11-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_conversationsession_alter_messageai_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageai',
            name='session_id',
        ),
        migrations.AddField(
            model_name='messageai',
            name='session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversationsession'),
            preserve_default=False,
        ),
    ]
