# Generated by Django 5.2.6 on 2025-11-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_messageai_session_id_messageai_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.etudiant'),
            preserve_default=False,
        ),
    ]
