# Generated by Django 5.2.6 on 2025-11-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversationsession_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationsession',
            name='owner',
        ),
    ]
