# Generated by Django 5.2.6 on 2025-11-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_conversationsession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.etudiant'),
            preserve_default=False,
        ),
    ]
